### ISSUE TITLE
cast() when Postgrex.CIDR?

### ISSUE THREAD

**Issue by micahwedemeyer** [adam12/ecto_network#2]
I'm still pretty unclear on how Ecto, Postgrex, and everything all work together, but I ran into an issue today that perhaps could be easily solved.

I have an array of CIDR addresses, defined as `{:array, EctoNetwork.CIDR}` in my Ecto model. When I try to add addresses to it, as strings like `127.0.0.1/32`, the first one is fine, but the subsequent ones fail. Upon inspection, I found that the list in the model attribute contained `Postgrex.CIDR` objects, not strings. So my list was something like:
`[%Postgrex.CIDR{foo}, "192.168.0.0/24"]` and Ecto wasn't too happy about that when I tried to update.

I was able to get around it by casting the Postgrex.CIDR objects to strings each time I add to the array, but I'm wondering if the correct approach would be to add a `cast` method to the EctoNetwork.CIDR class, like so:

`def cast(%Postgrex.CIDR{}=address), do: {:ok, decode(address)}`

or something along those lines?

**Comment by adam12** [comment]
Can you share a bit of the code you're using? I'm not using arrays of network types currently, so this is somewhat new to me.

I've pushed up a branch with a test to help debug this (maybe we're not on the same page). https://github.com/adam12/ecto_network/tree/issue-2/array-of-network-types

The test passes, so I'd like to see where it's busted.

**Comment by micahwedemeyer** [comment]
I'll try to set aside some time to clone the branch and put in a failing test that shows what I'm taking about.

**Comment by adam12** [comment]
I re-read your opening post and I think I have a better understanding now.

I pushed another update to that branch, which I think might solve your problem. Give it a try for me when you get a chance.

Thanks.

**Comment by micahwedemeyer** [comment]
Ha, I just got this. I pushed a branch and a PR. I’ll take a look at yours
and maybe we have the same idea.

**Comment by micahwedemeyer** [comment]
Yes, it looks like we're both on the same track. My only suggestion for your branch would be to test it with mixed content, both Postgrex and binary in the same array. That seems like a likely scenario, or at least, that's what I'm doing in my actual code. I calculate the CIDR, convert it to a "a.b.c.d/x" string, append it to the array, and then `update()`.

Also, as you see in my PR, perhaps both load and dump should have a pattern match case for `Postgrex.CIDR`? Honestly I don't know, but it _seems_ right...

**Comment by adam12** [comment]
I spoke with Jose and received some clarification. Will update shortly.

**Comment by micahwedemeyer** [comment]
Cool. I’m really curious. It would also make sense to me to pass these
things around as Postgrex.CIDR instead of strings. I generally prefer rich
data structures over raw strings anyway.

**Comment by adam12** [comment]
> It would also make sense to me to pass these
> things around as Postgrex.CIDR instead of strings.

This is how the new version will work, so you were on to something.

At José's suggestion, I moved the parsing to the `cast` function, and made `load` and `dump` return the values untouched.

This means that inserting directly into the database by passing a binary doesn't work, since it's not cast, so you now either have to pass the proper struct when directly inserting data, or use a changeset to cast appropriately.

New branch is here: https://github.com/adam12/ecto_network/tree/move-to-cast ([Diff](https://github.com/adam12/ecto_network/compare/issue-2/array-of-network-types...move-to-cast)). Give it a test when you get a second, and I'll get a release cut shortly if all checks out.

Thanks for the feedback and using the library!

**Comment by adam12** [comment]
Release v0.4.0 fixes this.

**Comment by micahwedemeyer** [comment]
Just a note that I upgraded to 0.4.0 today and it worked like a charm. Passing around actual Postgrex.CIDR structs is definitely a better way to go.

Thanks for all your hard work!
