### ISSUE TITLE
Empty netmask causes ArgumentError

### ISSUE THREAD

**Issue by mikl** [adam12/ecto_network#20]
I have a Live View with a form input to an IP address field, and I noticed it was neigh-impossible to input an address with a netmask without the server crashing.

When Ecto tries to validate an address like `1.2.3.0/` (ie. no number after the `/`), as would happen if you were trying to type `1.2.3.0/24`, the following error is thrown:

```
[error] GenServer #PID<0.860.0> terminating
** (ArgumentError) argument error
    :erlang.binary_to_integer("")
    (ecto_network) lib/ecto_network/inet.ex:37: EctoNetwork.INET.cast/1
    (ecto) lib/ecto/changeset.ex:566: Ecto.Changeset.cast_field/8
    (ecto) lib/ecto/changeset.ex:527: Ecto.Changeset.process_param/7
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/changeset.ex:504: Ecto.Changeset.cast/6
```

This is caused by the `String.to_integer(netmask)` call, netmask here being an empty string.

I wrote a failing test for this:

```elixir
  test "converts ipv4 with incomplete CIDR into changeset error" do
    changeset = Device.changeset(%Device{}, %{ip_address: "1.2.3.0/"})
    {:error, changeset} = TestRepo.insert(changeset)

    assert changeset.errors[:ip_address] ==
             {"is invalid", [type: EctoNetwork.INET, validation: :cast]}
  end
```

I wanted to fix the error, but I could not find a good way to do so without having to rewrite the whole `cast()` function, so I figured I’d better ask before doing so.

**Comment by adam12** [comment]
You could look at #19 for ideas on fixing it, as that PR fixed validation for mac addresses.

I wont' be able to fix it until the early New Year likely, but I'd accept a PR.

**Comment by mikl** [comment]
Ok, I wrote something that passes the tests. I’m still pretty new to Elixir, so there might well be a cleaner way of expressing this, but at least it should be fairly robust: #21
