### ISSUE TITLE
Postgrex.INET struct leaking

### ISSUE THREAD

**Issue by kanes115** [adam12/ecto_network#22]
It is not an issue per se, but rather a question about a reasoning behind a decision made. Namely, why do we allow the struct `Postgrex.INET` to leak from the type? Shouldn't it be transparent to the user of the lib (as it's a native data type?). This can happen because [load](https://github.com/adam12/ecto_network/blob/master/lib/ecto_network/inet.ex#L53) function returns this struct. If there was no particular reason behind this, I would more than happy to open a PR.

**Comment by adam12** [comment]
I don't remember it being a specific design decision.

I'd accept a PR. :+1:

**Comment by adam12** [comment]
Closing for now. If you still wish to submit a PR please feel free to do so.
