### ISSUE TITLE
INET type should not assign a netmask based on tuple size

### ISSUE THREAD

**Issue by AndrewDryga** [adam12/ecto_network#25]
I noticed that INET and CIDR implementations are the same, but it's not the correct way to handle them. INET is just an IP address and it should not have netmask auto-assigned ([here](https://github.com/adam12/ecto_network/blob/master/lib/ecto_network/inet.ex#L102)). Should we drop it?

The issue it's causing right now is that if we do any read operation it corrupts the Posgrex.INET struct, here is an example:
```elixir
# stored in database
# retrieved by Ecto.Adapters.SQL.query!(Repo, "SELECT * FROM devices")
%Postgrex.INET{address: {10, 3, 2, 2}, netmask: nil}

# returned by repo operations and corrupted due to mask-guessing
# retrieved by Repo.one(Device)
%Postgrex.INET{address: {10, 3, 2, 2}, netmask: 32}
``` 

If you are okay with the change I'll make a PR.

**Comment by adam12** [comment]
I'm not sure I'm seeing the issue, but it's been some time since I've used Elixir.

Could you make a failing test case? Perhaps that would help me understand.

**Comment by AndrewDryga** [comment]
@adam12 you can see the test and changes at https://github.com/firezone/ecto_network/

**Comment by adam12** [comment]
I'm still unsure about the drawbacks of this change, but I'll accept a PR for it and we can ship it as a minor semver bump.

**Comment by adam12** [comment]
I'm going to close this for now. If you're still willing to submit a PR, please go ahead.
