### ISSUE TITLE
Casting issue with MAC addresses

### ISSUE THREAD

**Issue by tchoutri** [adam12/ecto_network#7]
Hi @adam12 ! I'm using your library and an error happens when using your custom ecto type MACADDR:
The error says:
```
iex(3)> %Computer{name: "foobar", mac_address: "02:01:00:0A:00:FF"} |> NewApp.Repo.insert!
** (Ecto.ChangeError) value `"02:01:00:0A:00:FF"` for `NewApp.Computer.mac_address` 
in `insert` does not match type EctoNetwork.MACADDR

```
This is kinda super weird.

Here's the relevant data:

### My Schema
```Elixir
defmodule NewApp.Computer do
  use Ecto.Schema
  import Ecto.Changeset

  schema "computers" do
    field :name, :string
    field :mac_address, EctoNetwork.MACADDR
    timestamps()
  end
end

```

### My Migration
```Elixir
defmodule NewApp.Repo.Migrations.Computers do
  use Ecto.Migration

  def change do
    create table(:computers) do
      add :name, :string
      add :mac_address, :macaddr
    end
  end
end
```

It however works well when I manually transform the MAC address to a `Postgrex.MACADDR` struct…

**Comment by tchoutri** [comment]
Okay I was completely mistaken about the way to do it, and I forgot to use the `changeset` function. My bad for the disturbance. Thanks for your work :)

**Comment by adam12** [comment]
Glad you got it sorted :)
