### ISSUE TITLE
Automatically decoding the MACADDR struct when querying the Repo

### ISSUE THREAD

**Issue by tchoutri** [adam12/ecto_network#8]
Hi! It's me again ;)
I've come to need to have the MACADDR struct in its string format, and instead of using `Enum.map` to iter over the results of the Ecto queries to use `to_string`, I was wondering if it was acceptable to have this bit of code in [macaddr.ex](https://github.com/adam12/ecto_network/blob/master/lib/ecto_network/macaddr.ex#L11):

```Elixir
  @doc "Handle casting to Postgrex.MACADDR"
  def cast(%Postgrex.MACADDR{}=address) do
    {:ok, decode(address)}
  end
[…]
```
Instead of just returning the address.   
I'm quite a newbie in the Ecto.Type business, so I'd like your opinion as a maintainer about this behavior. Is is the right thing to do?

**Comment by adam12** [comment]
Hello again! 

I believe the functionality as written is correct.

We define protocols for both Elixir and Phoenix, so you might not need to call `to_string` explicitly, but rely on Elixir or Phoenix to call the appropriate protocol function.

**Comment by tchoutri** [comment]
Okay, I'm asking because I cannot find examples of automatic decoding for custom Ecto Types on the web (and the docs seem to consider this trivial), which is not as intuitive for me).

**Comment by adam12** [comment]
What are you trying to achieve exactly?

**Comment by tchoutri** [comment]
I'm trying to have the `mac_address` field of my models automatically converted from `Postgrex.MACADDR` to its String representation when I query the database for the models (like `Repo.get Computer, 1`)

**Comment by adam12** [comment]
I see. And using the implicit `to_string` that String.Chars protocol offers isn't a solution?

```elixir
@computer = Repo.get(Computer, 1)

IO.puts "The mac address is #{@computer.mac_address}"
# or <%= @computer.mac_address %> in a Phoenix HTML template
```

**Comment by adam12** [comment]
If this is still relevant and the `String.Chars` protocol isn't sufficient, please re-open.

**Comment by tchoutri** [comment]
Oh, sorry, I've been quite under the water these months.
The String.Chars protocol is all that I needed, but I was still seing the postgrex struct while in IEx.
Thanks for your time. :)
